### ISSUE TITLE
Error installing certificate on Laravel Forge

### ISSUE THREAD

**Issue by freekmurze** [erikrose/peep#131] opened 2016-03-03 15:14 UTC
Hi,

I tried to install a certificate via Laravel Forge on an Ubuntu server and got this error:

```
peep: (3, 1, 1)
python: '2.7.11 (default, Dec 15 2015, 16:46:19) 
[GCC 4.8.4]'
pip: '1.5.4'
Command line:  ['/tmp/tmp.FO5Yw7B5sh/peep.py', 'install', '-r', '/tmp/tmp.FO5Yw7B5sh/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.FO5Yw7B5sh/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.FO5Yw7B5sh/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.FO5Yw7B5sh/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.FO5Yw7B5sh/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.FO5Yw7B5sh/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '
'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 79: ordinal not in range(128)
```

How can this be solved?

**Comment by erikrose** [comment] 2016-03-03 16:17
Dupe of #127

**Closed by erikrose** 2016-03-03 16:17 UTC
