### ISSUE TITLE
[traceback] AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by rlr** [erikrose/peep#82] opened 2015-04-08 19:27 UTC
Kitsune is using peep 2.2. I get the following error when running with our vagrant setup:

```
==> default: Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
==> default: with the specifics so we can fix it:
==> default:
==> default: https://github.com/erikrose/peep/issues/new
==> default:
==> default: Here are some particulars you can copy and paste into the bug report:
==> default:
==> default: ---
==> default: peep: (2, 2, 0)
==> default: python: '2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'
==> default: pip: '6.1.1'
==> default: Command line:  ['/home/vagrant/kitsune/scripts/peep.py', 'install', '-r', '/home/vagrant/kitsune/requirements/default.txt', '--no-use-wheel']
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 876, in <module>
==> default:     exit(main())
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 848, in main
==> default:     return commands[argv[1]](argv[2:])
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 808, in peep_install
==> default:     for path in req_paths))
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 808, in <genexpr>
==> default:     for path in req_paths))
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 785, in downloaded_reqs_from_path
==> default:     path, options=EmptyOptions(), session=PipSession()))
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 774, in downloaded_reqs
==> default:     return [DownloadedReq(req, argv) for req in parsed_reqs]
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 351, in __init__
==> default:     self.__class__ = self._class()
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 650, in _class
==> default:     if self._actual_hash() not in self._expected_hashes():
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 263, in memoizer
==> default:     self._cache[func.__name__] = func(self)
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 615, in _actual_hash
==> default:     return hash_of_file(join(self._temp_path, self._downloaded_filename()))
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 263, in memoizer
==> default:     self._cache[func.__name__] = func(self)
==> default:   File "/home/vagrant/kitsune/scripts/peep.py", line 567, in _downloaded_filename
==> default:     if self._req.url is None
==> default:   File "/home/vagrant/virtualenv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 128, in url
==> default:     return self.link.url
==> default: AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by edmorley** [comment] 2015-04-10 13:11
Dupe of #80 - either roll back to pip v6.0.8 (or if you're using pip from virtualenv, then virtualenv v12.0.7) or cherrypick https://github.com/edmorley/peep/commit/ad6835e7f27cf8c0656e035eb17d2947ebf5088b in the meantime.

**Comment by willkg** [comment] 2015-04-10 13:19
Closing this as a duplicate of #80 now that I've renamed it.

**Closed by willkg** 2015-04-10 13:19 UTC
