### ISSUE TITLE
No matching distribution found for argparse==1.4.0 

### ISSUE THREAD

**Issue by mingjunyang** [erikrose/peep#119] opened 2016-02-16 10:04 UTC
./letsencrypt-auto --help
Bootstrapping dependencies for openSUSE-based OSes...
root's password:

Checking for new version...
Upgrading letsencrypt-auto 0.5.0.dev0 to 0.4.0...
Replacing letsencrypt-auto...
   sudo cp /tmp/tmp.A6LdvR8ENQ/letsencrypt-auto ./letsencrypt-auto
Creating virtual environment...
Installing Python packages...
No handlers could be found for logger "pip.index"
Had a problem while downloading and verifying Python packages:

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (3, 0, 0)
python: '2.7.9 (default, Dec 13 2014, 18:02:08) [GCC]'
pip: '7.1.2'
Command line:  ['/tmp/tmp.bGCYy6uJNh/peep.py', 'install', '-r', '/tmp/tmp.bGCYy6uJNh/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 862, in peep_install
    for path in req_paths))
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 862, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 839, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 420, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 699, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 655, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.bGCYy6uJNh/peep.py", line 608, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/home/mingjunyang/.local/share/letsencrypt/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for argparse==1.4.0 (from -r /tmp/tmp.bGCYy6uJNh/letsencrypt-auto-requirements.txt (line 1))

---

**Comment by erikrose** [comment] 2016-02-16 16:50
Duplicate of #117, fixed by #118

**Closed by erikrose** 2016-02-16 16:50 UTC

**Comment by edmorley** [comment] 2016-02-16 16:53
It's worth noting that it's fixed in the sense that peep no longer gives the scary misleading warning, but the root cause will still exist (since the root cause is unrelated to peep). See https://github.com/erikrose/peep/issues/117#issuecomment-182660817 for more details :-)

Once a new peep release is made (it's probably worth waiting until #116 is merged before we do that), I'll open a PR against letsencrypt to update to a peep where the confusing warning is fixed.
