### ISSUE TITLE
error using letsencrypt

### ISSUE THREAD

**Issue by diopralinato** [erikrose/peep#130] opened 2016-03-03 11:10 UTC
i just wrote "./letsencrypt-auto --help" and i've got this error:

---
peep: (3, 1, 1)
python: '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'
pip: '1.5.4'
Command line:  ['/tmp/tmp.QxN0Hta4K1/peep.py', 'install', '-r', '/tmp/tmp.QxN0Hta4K1/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.QxN0Hta4K1/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.QxN0Hta4K1/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.QxN0Hta4K1/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.QxN0Hta4K1/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.QxN0Hta4K1/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 79: ordinal not in range(128)

---

**Comment by cconover** [comment] 2016-03-03 15:31
I got the exact same error and debug output trying to run `./letsencrypt-auto renew`.

**Comment by erikrose** [comment] 2016-03-03 16:17
Dupe of #127

**Closed by erikrose** 2016-03-03 16:17 UTC
