### ISSUE TITLE
nice errors

### ISSUE THREAD

**Issue by Extreemhost** [erikrose/peep#124] opened 2016-02-22 21:20 UTC
peep: (3, 0, 0)
python: '2.7.3 (default, Mar 13 2014, 11:03:55) \n[GCC 4.7.2]'
pip: 'no __version__ attr'
Command line:  ['/tmp/tmp.FfLJb1VvRX/peep.py', 'install', '-r', '/tmp/tmp.FfLJb1VvRX/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 862, in peep_install
    for path in req_paths))
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 862, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 839, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 420, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 699, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 655, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.FfLJb1VvRX/peep.py", line 608, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pbr==1.8.1 (from -r /tmp/tmp.FfLJb1VvRX/letsencrypt-auto-requirements.txt (line 88))

**Comment by edmorley** [comment] 2016-02-23 12:30
Hi :-) This is a dupe of #117 / #119 / #121 / #123. For more details, see:
https://github.com/erikrose/peep/issues/123#issuecomment-186614233

**Closed by edmorley** 2016-02-23 12:30 UTC
