### ISSUE TITLE
here are some problem

### ISSUE THREAD

**Issue by Funnyang** [erikrose/peep#123] opened 2016-02-20 13:14 UTC
here are the report:
---
peep: (3, 0, 0)
python: '2.7.5 (default, Nov 20 2015, 02:00:19) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.UUBR4YyqXC/peep.py', 'install', '-r', '/tmp/tmp.UUBR4YyqXC/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 862, in peep_install
    for path in req_paths))
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 862, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 839, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 420, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 699, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 655, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.UUBR4YyqXC/peep.py", line 608, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for six==1.10.0 (from -r /tmp/tmp.UUBR4YyqXC/letsencrypt-auto-requirements.txt (line 165))

---

**Comment by edmorley** [comment] 2016-02-20 14:23
Thank you for filing, however this isn't due to peep (the message shown is wrong and is fixed in a newer version of peep) - see #117, #119, #121.

letsencrypt/letsencrypt#2486 will make letsencrypt-auto use this newer version of peep that shows a less confusing error message - however the root cause will remain (since it's unrelated to peep).

Please try upgrading to a newer Python and/or pip and file an issue against letsencrypt:
https://github.com/letsencrypt/letsencrypt/issues/new
(if this turns out to be a pip or Python version incompatibility, ideally letsencrypt would fail earlier with a suitable error message to that effect)

**Closed by edmorley** 2016-02-20 14:23 UTC
